replicaCount: 2
image:
  repository: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/flask-eks-infra
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
livenessProbe:
  httpGet:
    path: /health/live
    port: 5000
readinessProbe:
  httpGet:
    path: /health/ready
    port: 5000